# !/usr/bin/env python
# -*- coding: utf-8 -*-
# Author: Bobe_24@126.com

train_path = "../data/sample_data/train_file.txt"
test_path = "../data/sample_data/test_file.txt"
label_dict_path = "../data/sample_data/label_dict.txt"
word_model_path = "../data/model/100features_5minwords_10context"
char_model_path = "../data/model/100features_5minwords_10context_char"
word_pkl_path = "../data/dict.pkl"
char_pkl_path = "../data/char_dict.pkl"
unlabeled_path = "../data/unlabeled_data/"
pv_dm_model_path = "../data/model/pv_dm_400features_5minwords_10context"
pv_dbow_model_path = "../data/model/pv_dbow_400features_5minwords_10context"

word_lstm_model_path = "../data/model_trained/word_lstm.m"
cnn_model_path = "../data/model_trained/cnn_model.m"
c_lstm_model_path = "../data/model_trained/c_lstm.m"
lstm_char_model_path = "../data/model_trained/lstm_char.m"
lstm_sentence_model_path = "../data/model_trained/lstm_sentence.m"
cnn_char_model_path = "../data/model_trained/cnn_char.m"
cnn_sentence_model_path = "../data/model_trained/cnn_sentence.m"
lstm_w_c_model_path = "../data/model_trained/lstm_w_c.m"
lstm_w_s_model_path = "../data/model_trained/lstm_w_s.m"
lstm_c_s_model_path = "../data/model_trained/lstm_c_s.m"
cnn_w_c_model_path = "../data/model_trained/cnn_w_c.m"
cnn_w_s_model_path = "../data/model_trained/cnn_w_s.m"
cnn_c_s_model_path = "../data/model_trained/cnn_c_s.m"
c_cnn_model_path = "../data/model_trained/c_cnn.m"

test_label_path = "../data/predict_class/test_label.txt"
svm_tfidf_path = "../data/predict_class/svm_tfidf.txt"
svm_tfidf_prf_path = "../data/predict_class/svm_tfidf_prf.txt"
lstm_w_path = "../data/predict_class/lstm_w.txt"
lstm_w_prf_path = "../data/predict_class/lstm_w_prf.txt"
lstm_w_c_path = "../data/predict_class/lstm_w_c.txt"
lstm_w_c_prf_path = "../data/predict_class/lstm_w_c_prf.txt"
lstm_w_e_path = "../data/predict_class/lstm_w_e.txt"
lstm_w_e_prf_path = "../data/predict_class/lstm_w_e_prf.txt"

